[package]
name = "json_agregate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.204"
serde_json = "1.0.120"
tokio = { version = "1.39.1", features = ["full", "fs"] }
